%% download the meteor wind data from madrigal

%% Set inputs

code_fn = '~/data/meteor_winds/madrigal/mwr_madrigal_codes.xlsx';
outdir = '~/data/meteor_winds/madrigal/%s/';

%% Download
names = readtable(code_fn);
codes = names.Var1;
sitenames = names.Var2;
lats = names.Var4;
lons = names.Var5;

for i = 1:length(codes)
    try
    globalDownload('https://cedar.openmadrigal.org/', ...
        sprintf(outdir, strrep(sitenames{i}, ' ', '_')), ...
        'Alex+Chartier', ...
        'alex.chartier@jhuapl.edu', ...
        'APL', ...
        'netCDF4', ...
        datenum('01-Jan-1950 00:00:00'), ...
        datenum('31-Dec-2025 00:00:00'), ...
        codes(i), ...
        [], ...
        '', ...
        '')
    catch
        fprintf('Failed to get some of %s/n', sitenames{i})
    end
end

% codes
